### ISSUE TITLE
Dark theme should a global theme property

### ISSUE THREAD

**Issue by davinov** [ToucanToco/components#2]
Actually, `dark` is prop to all components.
It's not a problem for readability/maintenance (as it's factored in a mixin), but it still raises two concerns:
- it needs to be passed from parent to child, cluttering templates
- it should not differ from one component to another (but rather be defined globally)

**Comment by edlb** [comment]
@davinov I implemented my suggestion [here](https://github.com/ToucanToco/components/commit/9d890c4bf9fbfe0cc2a885497bb8c14183f42faf), what do you think ?

**Comment by davinov** [comment]
Hi! Sorry I missed your comment earlier
This is indeed a very clever trick! However, I fear that the link of props from parent to child may be broken if one of the component in the hierarchy doesn't have this prop.

> The issue with making dark global is that is most cases it concerns only part of the UI.
May be that's the culprit: IMO a UI should be totally light or totally dark, but it shouldn't have one and part of the components one theme and part the other. 
This is of course only my opinion, and could be discussed.

Anyway, as we don't have any product implementing a dark theme for now (and it would be quite a challenge to adapt all our charts for this also), maybe it's not the main point to focus on if we want to use this lib as soon as possible. What do you think?

**Comment by edlb** [comment]
The primary reason why I started implementing the dark theme is we **do** have part of our interface using a dark theme: the studio toolbar and all its children

**Comment by davinov** [comment]
Ahhhh that's true!
In my head is was more of a another color theme like primary.  

But we do have primary elements on dark parts on the UI, like Refresh data button or some switches. So :+1: 
Thanks for making that clear to me

**Comment by davinov** [comment]
In that case,we can close this issue. If it's for some parts of the UI, fine to inherit from it or declare it explicitly :)
