### ISSUE TITLE
Library should be bundled and published in npm for easy consumption

### ISSUE THREAD

**Issue by davinov** [ToucanToco/components#4]
- [x] Build the lib in a standalone way, not tied to the docs
- [x] Automatically build it with Continuous Integration
- [x] Publish on npm

**Comment by davinov** [comment]
First step: build done in vue-cli https://github.com/ToucanToco/components/pull/1

**Comment by edlb** [comment]
Second and third step done with GitHub actions: https://github.com/ToucanToco/components/blob/master/.github/workflows/npm-publish.yml
